# Generated by Django 4.2.9 on 2024-12-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(default='0xFF5687dd63d55b6B5990bD2ad27927d5b9DAA6c1', max_length=42, unique=True),
        ),
    ]
